version: '3.8'
services:
  jmd-processos:
    build: .
    ports:
      - "3000:80"
    restart: always
    container_name: jmd-processos
    volumes:
      - jmd_data:/app/data

volumes:
  jmd_data:
